### ISSUE TITLE
1.12 pre-release exception build 0.9.30.

### ISSUE THREAD

**Issue by smmmadden** [KaiKikuchi/QuickShop#124]
Are there changes required in the config file for 0.9.30?  This is using latest Spigot build for 1.12.
[14:39:44] [Server thread/INFO]: [QuickShop] Enabling QuickShop v0.9.30
[14:39:44] [Server thread/ERROR]: Error occurred while enabling QuickShop v0.9.30 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(Ljava/io/InputStream;)Lorg/bukkit/configuration/file/YamlConfiguration;
	at org.maxgamer.quickshop.Util.MsgUtil.loadCfgMessages(MsgUtil.java:48) ~[?:?]
	at org.maxgamer.quickshop.QuickShop.reloadConfig(QuickShop.java:456) ~[?:?]
	at org.maxgamer.quickshop.QuickShop.onEnable(QuickShop.java:136) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:376) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:326) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]

**Comment by KaiKikuchi** [comment]
You cannot update plugins without shutting down your server and then updating the jar, otherwise things will corrupt. Plugins like plugman etc cannot update plugins.

**Comment by smmmadden** [comment]
Really?  You are assuming I have no clue how to do this Kai.  The server was shutdown completely, the old jar file removed and the server restarted (multiple times before I reported the issue).  While I do have PlugMan as a plugin, that is NOT how I install new plugins.  Again, assuming doesn't resolve issues, request you reopen and determine the cause of the exception.

**Comment by KaiKikuchi** [comment]
> java.lang.NoSuchMethodError: org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(Ljava/io/InputStream;)Lorg/bukkit/configuration/file/YamlConfiguration;

This is a common issue that a lot of server administrators ask about the causes. Weird "NoSuchMethod" exception on methods that are definitely there are 99% times caused by either updated plugins without restarting the server, or the jar being corrupted (very less common).

I am sorry it looks like I triggered you and you responded with a very much defensive message, but this is all I could say.

Try this... download the jar again, reupload it to the server while the server is down, then start the server.  Other than this, I really do not know. The method is there so the fact your server cannot find a Bukkit method is beyond this plugin boundaries.

I even tested redownloading the jar file from Github and using an old test server with an old messages.yml file, and still works fine:
![image](https://cloud.githubusercontent.com/assets/8842403/26171534/91428768-3b45-11e7-8971-035b6a311a42.png)

**Comment by smmmadden** [comment]
Understood but keep in mind just because it works when you test it, does not mean it'll work for everyone else.  I've provided the full log file here. https://pastebin.com/ng1dwdYA
I downloaded the file, replaced the previous 0.9.30 jar file and restarted the server.  No changes made to anything else.  Is it possible there are hooks from QuickShop to any of the other plugins that have issues?  It would make more sense if it is.  I even deleted the entire QuickShop folder and restarted.  Here is the log for that one. https://pastebin.com/DbKTakUq

And to be sure it had nothing to do with PlugMan, I removed it completely.  No difference in startup.

**Comment by KaiKikuchi** [comment]
Not sure if you have noticed, but a lot of plugins are throwing an exception with the same issue. Did you update your server version recently?

**Comment by KaiKikuchi** [comment]
Nevermind. This means Bukkit/Spigot did something bad and broke configurations with all plugins.

**Comment by smmmadden** [comment]
yes, all the plugin failures have been reported on their respective sites.  The complete list is here: https://www.spigotmc.org/wiki/spigot-1-12-plugin-compatibility-list

**Comment by KaiKikuchi** [comment]
I mean that API change is quite bad. I understand why it is deprecated, but removing it is just dumb. Basically they're breaking compatibility with almost all plugins, and everyone will just fix it without changing anything. I'm extremely disappointed.

**Comment by KaiKikuchi** [comment]
Fixed in v.0.9.31

**Comment by KaiKikuchi** [comment]
Such API changes are extremely rare and should be avoided as much as possible. Especially because this does not help developers at all. I hope they'll decide to revert this change in a future release, otherwise they're pushing developers away from Bukkit (Sponge API is becoming much stronger than before). Bukkit is still popular because there are a lot of plugins. In my opinion, breaking the compatibility with almost all plugins will reduce Bukkit popularity.

Anyway, I couldn't think it was really such an API change so I apologize I couldn't check it wasn't that before replying... but I receive that from a lot of server owners so it was an automatic response, especially because I didn't have time to look at it at that time.

**Comment by smmmadden** [comment]
not a problem Kai, I do appreciate you investigating further into it and coming up with a fix so quickly.  This isn't anything new for Mojang or Spigot for that matter, every release since 1.8 (when I started) has all resulted in plugin failures with the 1.11.x it broke the SQLite drivers due to their upgrading the core product.  Now that Mojang has also significantly upgraded Guava to 21.0, it's a major leap forward on top of now requiring Java 8 which everyone should be using by now anyway.  Everything trickles down to you guys unfortunately, and the only way for them to stop this insane trip is to push back directly on Mojang. 

Some changes make sense, but I think we all agree, we need to stop breaking backward compatibility and do the right thing for a change.  Being in the software business for over 25 years, it's a tough battle and I do so every day. :-)  Sorry I came across harsh earlier, been sick the last two days so my patience was much thinner than it should be.
