### ISSUE TITLE
Some Suggestions 

### ISSUE THREAD

**Issue by KrohmKoala** [KaiKikuchi/QuickShop#30]
Hey i have some things to suggest to you (sorry for my english i'm french ^^)
1: add some members to a chest to be some people to fill the chest

2: if there's members, anyone get his part of the price

3: change the account where the money go

4: add the support of acacia and big oak (whose call "LOG2" for now)

5: add the ingame help ^^

**Comment by KaiKikuchi** [comment]
Hello. Thank you for your suggestions.
1, 2, 3: I was already thinking about something similar, but at this moment it can't be done on QuickShop because it requires too much work.

4: Unfortunately, QuickShop uses Bukkit internal names... and that's what Bukkit returns. That's something that should be fixed on Bukkit API.

5: there's already an ingame help/commands list
