### ISSUE TITLE
Problem When Creating Shops

### ISSUE THREAD

**Issue by TechnoGeek123-321** [KaiKikuchi/QuickShop#79]
Whenever I create a shop it does this:
![2016-08-22_15 25 24](https://cloud.githubusercontent.com/assets/9282760/17868399/b5fe61d6-687c-11e6-96c5-a992b74cf826.png)
To be clear this is one attempt at creating a shop.
Then I type a worth in chat and nothing happens. Plugins:
![2016-08-22_15 26 30](https://cloud.githubusercontent.com/assets/9282760/17868437/e7c126ae-687c-11e6-9ac3-b355b3ce2906.png)
Running on Spigot 1.10.2

**Comment by KaiKikuchi** [comment]
Usually, this is caused by an "aggressive" chat plugin. You're using Herochat, and that should be supported by QuickShop.

I am going to improve the "/qs create" command so you can specify the price in the command too, so you won't need to click the chest and specify the price on the chat.

Also I think you should post your server log of your server start (especially the part where QuickShop loads... it should say that Herochat has been detected).

**Comment by KaiKikuchi** [comment]
Improved the command in version 0.9.23.
